### ISSUE TITLE
Depend on js.bootstrap instead of including bootstrap.min.css?

### ISSUE THREAD

**Issue by disko** [Kotti/deform_bootstrap#1]
Is there a specific reason for including bootstrap.min.css instead of depending on the fanstatic based js.bootstrap package (http://pypi.python.org/pypi/js.bootstrap/1.4)?

**Comment by dnouri** [comment]
Haven't thought about that.  I included the CSS only to get the deformdemo working.

In my app (Kotti) I'm using my own copy of these resources.  I should probably look into using js.bootstrap there.  For deform_bootstrap itself, the advantage of including resources would be that it becomes easier for developers to see how to include resources.  The alternative is having them go and depend on js.bootstrap themselves.

What do we think?

**Comment by disko** [comment]
I see your point.

Also depending on js.bootstrap would not only introduce a new dependency plus an additional indirect dependency to fanstatic (including its own dependencies), but also lead developers to using fanstatic even if they don't want to (although they should IMHO, but that's for sure already to opinionated).

**Comment by dnouri** [comment]
Agreed, then.
