### ISSUE TITLE
What’s the schedule for the next PyPI release?

### ISSUE THREAD

**Issue by dairiki** [Kotti/deform_bootstrap#23]
It would be convenient (for me, at least) to have some of the recent features (Chosen, bootstrap-datepicker.css) in PyPI.

It is not a pressing issue, but here is one vote for a release.

**Comment by disko** [comment]
For me, too :)

+1

**Comment by dnouri** [comment]
It's out!

**Comment by dairiki** [comment]
That was quick, as usual.  Thank you!
