### ISSUE TITLE
Sequence widget not working (javascript dom manipulation)

### ISSUE THREAD

**Issue by domenkozar** [Kotti/deform_bootstrap#35]
http://deformdemo.repoze.org/sequence_of_sequences/

Adding another item won't work.

**Comment by dnouri** [comment]
Seems to work for me.  I have a checkout of deform_bootstrap and I've tried the demo.ini app therein, and tried some of the examples.

Seems to also work for the older version of the demo running at http://deformdemo.xo7.de/sequence_of_sequences/

Have any more clues for me?

**Comment by domenkozar** [comment]
It seems I forgot to include deform_bootstrap.js. Maybe we should provide a snippet for pyramid that includes all needed? And people can remove stuff from that list instead of figuring out the minimum needed.

**Comment by dnouri** [comment]
cc @disko

**Comment by dnouri** [comment]
@iElectric I'm fine with a snippet (and a little reference in readme?) if you want to pull up a pull request.

**Comment by domenkozar** [comment]
Will do.

**Comment by domenkozar** [comment]
Actually with deform2 and the merge, this can be closed as far I'm concerned.
