### ISSUE TITLE
Demo is not bootstraped

### ISSUE THREAD

**Issue by brodul** [Kotti/deform_bootstrap#38]
I installed demo. It's not bootstraped.

**Comment by dnouri** [comment]
Ping @disko -- fanstatic?

**Comment by disko** [comment]
No, there is no such thing like fanstatic in deform_bootstrap ;-)

At first look it seems as if the `deform_bootstrap.demo.includeme` doesn't get executed for a reason that I don't understand.

**Comment by dnouri** [comment]
This seems to work for me.

I got the recent `colander`, `deform`, `deformdemo` from Git and installed it.  Then I ran `bin/pserve demo.ini` and I got a bootstrapped demo.

I've updated the docs, which were referring to an older version of `deformdemo`.  Maybe that was the issue?  https://github.com/dnouri/deform_bootstrap/commit/336ccb2283d45659c95fba7aa3201d50515c3c08
