### ISSUE TITLE
Merge deform_bootstrap into deform

### ISSUE THREAD

**Issue by cguardia** [Kotti/deform_bootstrap#50]
At PyCon, we are looking into merging deform_bootstrap into deform and releasing it as deform 2. Would you be OK, with that?

**Comment by dnouri** [comment]
Sure!

**Comment by belasin** [comment]
In the light of the above, I have jquery upload widget and select 2 widgets that i would like to contribute. Should i hold off until this has been finalised?

**Comment by disko** [comment]
I think none of deform_bootstrap's maintainers is directly involved in this.  @cguardia: can you answer @jpunwin's question?

**Comment by cguardia** [comment]
I started with the merge at PyCon, but first we had to close as many issues as possible on deform, so I didn't have enough time to finish. I think, @jpunwin, that if if you have some contributions ready you should do it now, as the time frame for the move is uncertain at this point. There's a summer sprint coming where conceivably the merge could happen, but it's not a sure thing at this point.

**Comment by dnouri** [comment]
This is happening in http://github.com/Pylons/deform/tree/deform2
