### ISSUE TITLE
Placeholder Support

### ISSUE THREAD

**Issue by belasin** [Kotti/deform_bootstrap#53]
Hi would be nice if we can configure a placeholder for the widgets

``` python
        widget=TypeaheadInputWidget(
            size=60,
            min_length=3,
            placeholder="Agent",
            values='/agents/list.json'),
        description='Provide the AgentID or Agent Name')
```

**Comment by belasin** [comment]
I thought this may be a good idea until I went through the systems. This is going to be a lot more complicated than I anticipated.

**Comment by tisdall** [comment]
There's support for this already on ChosenMultipleWidget which you can see in the template for that widget.
