### ISSUE TITLE
Missing clausing div in template

### ISSUE THREAD

**Issue by tonthon** [Kotti/deform_bootstrap#69]
In the mapping.pt template : 

``` html
<div tal:condition="field.description">
    ${field.description}
```

is missing the clausing div.
Example of consequence : 
If I introduce the mappingSchema in a sequenceSchema, the appendsequence button is not working.

**Comment by dnouri** [comment]
It's a little abstract.  Would you want to send a pull request?

**Comment by tonthon** [comment]
Here it is : https://github.com/Kotti/deform_bootstrap/pull/70
